version: '3.8'

services:
  mysql:
    image: 'bitnami/mysql:8.0'
    container_name: moodify_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: moodify_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true

volumes:
  mysql_data:
    driver: local